# update_fastlane

###
###  Flutter
###

platform :flutter do
  desc "runs pull request flow"
  lane :pr do
    sh "cd .. && fastlane/scripts/tests.sh"
    sh "cd .. && flutter analyze > flutter_analyze_report.txt || true"
  end
end
