name: Mob-flutter Pull Request Flow

# triggers
on:
  push:
    branches:
      - development
  pull_request:
    paths: 
      - 'lib/**'
      - 'server_login/**'
      - 'firebase_login/**'
      - 'Gemfile'

jobs:
  pr:
    name: Pull Request Check
    runs-on: macos-latest
    steps: 
      - name: Checkout Branch
        uses: actions/checkout@v2.3.2
        
      - name: Setup Flutter Stable Channel
        uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'stable'

      - name: Cache Fastlane dependencies
        uses: actions/cache@v2
        env:
          fastlane-cache-key: fastlane-cache
          fastlane-path: ~/.gem
        with:
          path: ${{ env.fastlane-path }}
          key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}

      - name: Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          flutter-cache-key: flutter-cache
          flutter-path: ~/.pub-cache
        with:
          path: ${{ env.flutter-path }}
          key: ${{ runner.os }}-build-${{ env.flutter-cache-key }}
          restore-keys: ${{ runner.os }}-build-${{ env.flutter-cache-key }}

      # run Fastlane lane pr
      - name: Run Lint and Tests
        run: bundle exec fastlane flutter pr
